### ISSUE TITLE
Showing error .csv file not correct but it is correct!

### ISSUE THREAD

**Issue by rmahmadkhan** [DSC-UIT-khi/DSC-Platform-Extension#4]
During my use of DPE, I have noticed that error messages are not specific to the cause of the error.
For example, if there is an internet issue during the upload, you'll get a message about the CSV file columns.
If something else happens, you get the error message about "make sure event exists".
I hope this might help to make it better.

**Comment by rawheel** [comment]
It is due to chrome drive, chrome just updated the version so you have to update the chrome driver as well you can do it by watching the tutorial by going to the warnings tab.
